version: "3.5"

services:
  postgresql:
    image: postgres:14.3
    env_file:
      - env.d/development/postgresql

  mysql:
    image: mysql:8.0
    env_file:
      - env.d/development/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    image: magnify:development
    env_file:
      - env.d/development/common
      - env.d/development/${DB_HOST:-postgresql}
    volumes:
      - .:/app
      - ./data/static:/data/static
      - ./data/media:/data/media
      - ./data/smedia:/data/smedia
      - ./src/django-cms/cms:/usr/local/lib/python3.10/site-packages/cms
    depends_on:
      - "${DB_HOST:-postgresql}"
    stdin_open: true
    tty: true

  nginx:
    image: nginx
    ports:
      - "8070:8070"
    volumes:
      - ./docker/files/etc/nginx/${NGINX_CONF:-conf.d}:/etc/nginx/conf.d:ro
    depends_on:
      - app

  node:
    image: circleci/node:14
    working_dir: /app/src/frontend
    user: "${DOCKER_USER:-1000}"
    volumes:
      - .:/app

  crowdin:
    image: crowdin/cli:3.5.5
    volumes:
      - ".:/app"
    env_file:
      - env.d/development/crowdin
    user: "${DOCKER_USER:-1000}"
    working_dir: /app

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:6.0-debian-10
    depends_on:
      - redis-primary
      - redis-replica1
      - redis-replica2
    environment:
      - REDIS_MASTER_HOST=redis-primary

  redis-primary:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master

  redis-replica1:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
    depends_on:
      - redis-primary

  redis-replica2:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
    depends_on:
      - redis-primary

  dockerize:
    image: jwilder/dockerize
